name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Build and push Docker image
            uses: docker/build-push-action@v5.1.0
            with:
              context: .
              platforms: linux/amd64, linux/arm64/v8
              push: ${{ github.event_name != 'pull_request' }}
              load: false
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              cache-from: type=gha
              cache-to: type=gha,mode=max


